# Generated by Django 4.0.3 on 2022-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appt_date_time',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
